spring.main.web-application-type=none
# Couchbase configuration
spring.couchbase.connection-string=couchbase://192.168.5.212
spring.couchbase.username=Administrator
spring.couchbase.password=Bonyan123
spring.couchbase.env.timeouts.connect=20s
couchbase.operation.timeout=60
spring.couchbase.env.timeouts.key-value-durable=60s


spring.data.couchbase.bucket-name=rtpBucket
profileIdsBucket=idBucket
profileIdsTemporaryBucket=tempIdBucket

# BI information
bi.data.separator=|
bi.header.separator=,
bi.file.path=/home/snow/Downloads/BI_Sample/split_to_5mil/part_ac
header.file.path=/home/snow/Downloads/BI_Sample/test/BiHeaders

mapping.yaml.path=classpath:templates/bi-to-profile-mapping.yaml
profile.template.path=classpath:templates/profile.template.json
msisdn.template.path=classpath:templates/msisdn.template.json


# Batch and thread configuration
cb-batchSize=3000
psql-batchSize=3000
thread-count=200

# PostgreSQL configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://192.168.5.212:5432/rtp
spring.datasource.username=rtp
spring.datasource.password=Bonyan123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# HikariCP settings for PostgreSQL
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=40
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.auto-commit=false
