package com.example.cbprofileutils.couchbase.service;

import com.example.cbprofileutils.couchbase.entity.PsqlProfileEntity;
import com.example.cbprofileutils.couchbase.repository.PsqlProfileRepository;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class PsqlProfileIdsService {
    private static final long DEFAULT_PROFILE_TYPE_ID = 52L;
    // Adjust if your naming rule changes
    private static final String NAME_PREFIX = "FAA_";

    private final PsqlProfileRepository repo;

    public PsqlProfileIdsService(PsqlProfileRepository repo) {
        this.repo = repo;
    }

    /** Returns id if (name, profileTypeId) exists, else null. */
    @Transactional(readOnly = true)
    public Long getIdIfExists(String msisdn, Long profileTypeId) {
        String name = normalizeName(msisdn);
        return repo.findFirstByNameAndProfileTypeId(name, requireProfileType(profileTypeId))
                .map(PsqlProfileEntity::getId)
                .orElse(null);
    }

    /**
     * Returns id for (name=FAA_<msisdn>, profile_type_id). If missing, inserts a new row
     * (optionally with parentId) and returns the generated id.
     * Concurrency-safe: relies on unique (name, profile_type_id) and retries on conflict.
     */
    @Transactional
    public Long getOrCreateId(String msisdn, Long profileTypeId, Long parentId) {
        String name = normalizeName(msisdn);
        Long typeId = requireProfileType(profileTypeId);

        // Fast path: read if present
        return repo.findFirstByNameAndProfileTypeId(name, typeId)
                .map(PsqlProfileEntity::getId)
                .orElseGet(() -> {
                    try {
                        // Not found -> create
                        PsqlProfileEntity e = new PsqlProfileEntity();
                        e.setName(name);
                        e.setProfileTypeId(typeId);
                        e.setParentId(parentId);
                        // id is generated by profile_id_seq (per your entity mapping)
                        return repo.saveAndFlush(e).getId();
                    } catch (DataIntegrityViolationException race) {
                        // Another tx created it concurrently: re-read and return
                        return repo.findFirstByNameAndProfileTypeId(name, typeId)
                                .map(PsqlProfileEntity::getId)
                                .orElseThrow(() ->
                                        new IllegalStateException("Concurrent insert detected but row not found on re-read"));
                    }
                });
    }

    /** Convenience overload w/o parentId. */
    public Long getOrCreateId(String msisdn) {
        return getOrCreateId(msisdn, DEFAULT_PROFILE_TYPE_ID, null);
    }

    // --- helpers ---

    private String normalizeName(String msisdn) {
        if (msisdn == null || msisdn.isBlank()) {
            throw new IllegalArgumentException("msisdn must not be null/blank");
        }
        String trimmed = msisdn.trim();
        if (trimmed.regionMatches(true, 0, NAME_PREFIX, 0, NAME_PREFIX.length())) {
            // normalize to exact casing "FAA_"
            return NAME_PREFIX + trimmed.substring(NAME_PREFIX.length());
        }
        return NAME_PREFIX + trimmed;
    }

    private Long requireProfileType(Long profileTypeId) {
        if (profileTypeId == null) {
            throw new IllegalArgumentException("profileTypeId must not be null");
        }
        return profileTypeId;
    }
}
